# Generated by Django 5.1.3 on 2025-06-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_book_available_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
